### ISSUE TITLE
Escaped fragment SEO support

### ISSUE THREAD

**Issue by dmyers** [userdeck/wordpress-plugin#1]

**Comment by dustinbolton** [comment]
Yeah; post/page options are still the only realistic way to handle this issue... WordPress still hasn't addressed that issue with using shortcodes.  There are concerns about performance impacts when waiting to output to the browser until all of the posts' shortcodes are parsed.  I've seen some plugins address this with output buffering but that's a quite heavy-handed approach to hijack all of WordPress for a single plugin.
